pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker {
          image 'maven:3.9.6-eclipse-temurin-21'
        }
      }
      environment {
        JAVA_HOME = '/opt/java/openjdk'
        PATH = "${JAVA_HOME}/bin:$PATH"
      }
      steps {
        sh 'echo $JAVA_HOME'
        sh 'java -version'
        sh 'mvn --version'
      }
    }

    stage('Front-end') {
      agent {
        docker {
          image 'node:16-alpine'
        }
      }
      steps {
        sh 'node --version'
        sh 'npm --version'
      }
    }
  }
}
